name: Deploy Client
run-name: Client deployment triggered by @${{ github.actor }}

on:
  push:
    branches:
      - main
    paths:
      - 'source/client/**'

jobs:
  Placeholder:
    runs-on: [ubuntu-latest]
    steps:
      - name: Deploy to Netlify
        run: curl ${{ secrets.NETLIFY_DEPLOY_WEBHOOK_URL }}