name: JSDocs Automation

on:
  push:
    branches: [main,dev]
jobs:
  jsdocs:
    name: Generate JSDocs
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci

      - name: Create JSDocs Output
        run: npm run jsdoc