name: Pull Request CI Pipeline [Client]
run-name: PR CI triggered by @${{ github.actor }} [Client]

on:
  pull_request:
    branches:
      - main

jobs:
  Jest:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Move to client subdirectory
        run: cd source/client
      - name: "[DEBUG] - LIST FILES IN CURRENT DIRECTORY"
        run: ls
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  ESLint:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Move to client subdirectory
        run: cd source/client
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint
        run: npm run lint
  Prettier:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Move to client subdirectory
        run: cd source/client
      - name: Instsall dependencies
        run: npm ci
      - name: Run Prettier
        run: npm run prettier