name: Pull Request CI Pipeline [Client]
run-name: PR CI triggered by @${{ github.actor }} [Client]

on:
  pull_request:
    branches:
      - main
    paths:
      - 'source/client/**'

defaults:
  run:
    working-directory: ./source/client

jobs:
  Test:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
  Lint:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run ESLint with Prettier
        run: npm run lint