name: Pull Request CI Pipeline [Server]
run-name: PR CI triggered by @${{ github.actor }} [Server]

on:
  pull_request:
    branches:
      - main

jobs:
  Temporary:
    runs-on: [ubuntu-latest]
    steps:
      - name: Check out code 
        uses: actions/checkout@v4
      - name: Move to server subdirectory
        run: cd source/server
      - name: Exit
        run: echo "exiting" && exit 0